### PR TITLE
avoid compilation problems introduced in d06b4ac

### PR DESCRIPTION
**Pull request by mohrm**
The refactoring in d06b4ac caused a [compilation error] (https://travis-ci.org/nikita-volkov/list-t/jobs/108771718) because apparently the new code tries to apply `fmap` on something which is a Monad but not a Functor. I think something like that can happen since [the Functor-Applicative-Monad proposal was realized in GHC](https://wiki.haskell.org/Functor-Applicative-Monad_Proposal). My proposal fixes this problem by using `liftM` instead of `fmap`.

### CODE REVIEW

**Comment by mohrm** [comment]
Okay, I have to correct myself: Your code works but only since GHC 7.10 because before fmap was not applicable to Monads...
So it's more a backwards compatibility issue...
