### ISSUE TITLE
fails to build with GHC-8.0

### ISSUE THREAD

**Issue by phadej** [nikita-volkov/list-t#8]
as `Control.Monad.IO.Class` is moved to base, package has to explicitly depend on it, otherwise will fail with 
```
library/ListT.hs:43:1: error:
    Failed to load interface for ‘Control.Monad.IO.Class’
    It is a member of the hidden package ‘base-4.9.0.0’.
```

I also made a revision for the latest version: https://hackage.haskell.org/package/list-t-0.4.6.1/revisions/

**Comment by nikita-volkov** [comment]
Thanks. The fixed version is released now.
